version: '3.11'
services:
  coffeerec_app:
    container_name: coffeerec_app
    restart: always
    env_file: .env
    build: .
    ports:
      - "8080:8080"
    networks:
      - web_network
networks:
  web_network:
    driver: bridge
 